# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package.json and tsconfig.json
COPY package.json ./
COPY tsconfig.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Install Node.js type definitions for TypeScript
RUN npm install --save-dev @types/node

# Copy the source and env example files
COPY src ./src
COPY env.example ./.env.example

# Build the TypeScript source
RUN npm run build

# Default command to start the MCP server
CMD ["node", "dist/start.js"]
